# Generated by Django 6.0.1 on 2026-01-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("public", "Public (No authentication required)"),
                    ("authenticated", "Authenticated users only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="allow_update",
            field=models.BooleanField(
                default=False,
                help_text="Allow authenticated users to update their submission",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="single_submission",
            field=models.BooleanField(
                default=False, help_text="Allow only one submission per user"
            ),
        ),
    ]
