# Generated by Django 6.0.1 on 2026-01-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0002_form_access_level_form_allow_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this form",
                null=True,
                upload_to="form_images/",
            ),
        ),
    ]
