# Generated by Django 6.0.1 on 2026-01-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0004_alter_formfield_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="admin_only",
            field=models.BooleanField(
                default=False, help_text="Only admin or facadmin can edit this field"
            ),
        ),
    ]
