# Generated by Django 6.0.1 on 2026-01-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0005_add_admin_only_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Bootstrap icon class (e.g., bi-person, bi-envelope)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("textarea", "Textarea"),
                    ("select", "Select"),
                    ("radio", "Radio"),
                    ("checkbox", "Checkbox"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("phone", "Phone"),
                    ("url", "URL"),
                    ("password", "Password"),
                    ("hidden", "Hidden"),
                    ("file", "File"),
                    ("select_faculte", "Select Faculte"),
                    ("select_domaine", "Select Domaine"),
                    ("select_specialite", "Select Specialite"),
                    ("select_etablissement", "Select Etablissement"),
                    ("panel", "Panel (Field Group)"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
