# Generated by Django 6.0.1 on 2026-01-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0006_add_panel_and_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="background_color",
            field=models.CharField(
                blank=True,
                help_text="Background color for the field (e.g., lightblue, #f0f0f0)",
                max_length=20,
            ),
        ),
    ]
